---

- hosts: localhost
  connection: local
  gather_facts: true

  roles:
    - cloudform-launch
    - ec2-provision-groups
    - { role: ec2-provision-instance, vpc_subnet_id: "{{bastion_subnet_id}}", group: "{{bastion_group}}" }

- name: Configure natvpn instance(s)
  hosts: tag_Name_natvpn_hackoregon
  user: ubuntu
  become: yes

  roles:
    - webmin
    - iptables
    - makevpn
    - vpnusers
