---

- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    instance_type: t2.nano
    count: 1
    assign_public_ip: yes
    vpc_subnet_id: subnet-a0121ed7
    image: ami-9abea4fb
    instance_tags: '{"Name":"{{ app_name }}_{{ server_env }}","Role":"{{ app_name }}"}'
    app_name: natvpn
    server_env: prod
    group: '{{app_name}}_{{server_env}}'

    vpc_network: 10.80.0.0
    vpc_mask: 255.255.0.0
    vpn_email: "bill@mcgair.com"
    ca_name: "HackOregonCA"
    vpn_name: "HackOregonVPN"
    vpn_org: "HackOregon"

    security_groups:
      - sg_name: "{{group}}"
        sg_description: "ansg"
        sg_rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: "0.0.0.0/0"
        - proto: udp
          from_port: 1194
          to_port: 1194
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 10000
          to_port: 10000
          cidr_ip: 24.21.200.124/32
  roles:
    - ec2-provision-group
    - ec2-provision-instance

- name: Configure instance(s)
  hosts: thisrun
  user: ubuntu
  become: yes

  roles:
    - webmin
    - iptables
    - makevpn

#- include: natvpn-configure.yml
