---

- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    instance_type: t2.micro
    count: 1
    assign_public_ip: yes
    vpc_subnet_id: subnet-a0121ed7
    image: ami-9abea4fb
    instance_tags: '{"Name":"{{ application }}_{{owner}}","Role":"{{ application }}"}'
    application: natvpn
    owner: hackoregon
    group: '{{application}}_{{owner}}'

    security_groups:
      - sg_name: "{{group}}"
        sg_description: "ansg"
        sg_rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: "0.0.0.0/0"
        - proto: udp
          from_port: 1194
          to_port: 1194
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 10000
          to_port: 10000
          cidr_ip: 0.0.0.0/0
  roles:
    - ec2-provision-instance
    - webmin
    - iptables
    - makevpn
    - snap-ami
    - ec2-term
