---

- hosts: localhost
  connection: local
  gather_facts: true

  vars:
    region: "{{ lookup('env', 'AWS_REGION') }}"
    image_name: "aws-marketplace/amzn-ami-2015.09.f-amazon-ecs-optimized-*"
    image_owner: ""

    cluster_name: "ecs-cluster"
    instance_type: "t2.micro"
    instance_monitoring: "no"
    health_check_period: "300"
    health_check_type: "EC2"
    min_size: 1
    max_size: 3
    desired_capacity: 1
    replace_all_instances: "yes"

  pre_tasks:
    - include_vars: "{{playbook_dir}}/group_vars/{{region}}"

  roles:
    - ec2-provision-ecs
