---

- hosts: localhost
  connection: local
  gather_facts: true


  vars:
    region: "{{ lookup('env', 'REGION') }}"
    idempotent_id: "{{ lookup('env', 'BASTION_IDEMPOTENT_ID') }}"
    instance_type: t2.nano
    count: 1
    assign_public_ip: yes
    image_name: "{{ lookup('env', 'BASTION_IMAGE_NAME') }}"
    image_owner: "{{ lookup('env', 'BASTION_IMAGE_OWNER') }}"
    wait: yes
    instance_tags: '{"Name":"{{application}}_{{owner}}","Role":"{{application}}"}'
    source_dest_check: "no"
    application: natvpn
    owner: hackoregon
    bastion_group: '{{application}}_{{owner}}'
    id: "{{bastion_group}}{{idempotent_id}}}"

  pre_tasks:
    - include_vars: "{{playbook_dir}}/group_vars/{{region}}"

  roles:
    - { role: ec2-provision-groups }
    - { role: aws-provision-iam }
    - { role: ec2-provision-instance, vpc_subnet_id: "{{dmza_subnet_id}}", group: "{{bastion_group}}" }

- name: Configure natvpn instance(s)
  hosts: tag_Name_natvpn_hackoregon
  user: ubuntu
  become: yes
  vars:
    region: "{{ lookup('env', 'REGION') }}"

  pre_tasks:
    - include_vars: "{{playbook_dir}}/group_vars/{{region}}"

  roles:
    - webmin
    - iptables
    - makevpn
    - vpnusers
