---
- name: launch a cloudformations stack
  cloudformation:
    stack_name="{{stack_name}}-stack"
    state="{{state}}"
    region="{{region}}"
    disable_rollback="{{disable_rollback}}"
    template="{{json_template}}"
  args:
    template_parameters:
      KeyName: "{{keypair}}"
      SSHLocation: "{{mgmt_ip}}"
      Owner: "{{owner}}"
      VPCName: "{{stack_name}}"
      CIDR: "{{vpc_base}}.0.0/{{vpc_mask}}"
      CIDRdmzA: "{{vpc_base}}.1.0/{{subnet_mask}}"
      CIDRdmzB: "{{vpc_base}}.2.0/{{subnet_mask}}"
      CIDRdmzC: "{{vpc_base}}.3.0/{{subnet_mask}}"
      CIDRprivA: "{{vpc_base}}.10.0/{{subnet_mask}}"
      CIDRprivB: "{{vpc_base}}.20.0/{{subnet_mask}}"
      CIDRprivC: "{{vpc_base}}.30.0/{{subnet_mask}}"
      CIDRdbA: "{{vpc_base}}.110.0/{{subnet_mask}}"
      CIDRdbB: "{{vpc_base}}.120.0/{{subnet_mask}}"
      CIDRdbC: "{{vpc_base}}.130.0/{{subnet_mask}}"
  register: stack

- ec2_vpc_subnet_facts:
    region: "{{region}}"
    filters:
      vpc-id: "{{stack.stack_outputs.VPCId}}"
      "tag:Name": "dmz-A"
  register: dmza_facts

- set_fact:
    vpc_id: "{{stack.stack_outputs.VPCId}}"
- set_fact:
    bastion_subnet_id: "{{dmza_facts.subnets.0.id}}"
