---

# stack defaults
group_vars_path: "Users/billm/repos/playbooks/group_vars/"
stack_name: "HackOregon"
owner: "Bill McGair"
state: "present"
region: "us-west-2"
disable_rollback: "yes"
keypair: "xaas-or"
json_template: "roles/cloudform-launch/files/vpc_build_no_bastion.json"
mgmt_ip: "24.21.200.124/32"
vpc_base: "10.10"
vpc_mask: "16"
vpc_mask_long: "255.255.0.0"
subnet_mask: "20"

# create all security groups
security_groups:
  - sg_name: "default"
    sg_description: "default allow ssh"
    sg_rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0

  - sg_name: "{{bastion_group}}"
    sg_description: "Bastion SG"
    sg_rules:
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: "0.0.0.0/0"
    - proto: udp
      from_port: 1194
      to_port: 1194
      cidr_ip: 0.0.0.0/0
    - proto: tcp
      from_port: 10000
      to_port: 10000
      cidr_ip: "{{mgmt_ip}}"

# vpn defaults
# allocate an eip and assign here
# to persist vpn addr across relaunches
# of the natvpn box
vpn_ip: 52.36.212.252
vpn_name: {{stack_name}}VPN
vpn_org: {{stack_name}}
vpn_OU: DevOps Division
vpn_CN: hackoregon.org
vpn_city: Portland
vpn_state: OR
vpn_country: US
ca_name:  {{stack_name}}CA
vpn_email: bill@mcgair.com
