---
- name: launch an ec2 instance
  ec2:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    instance_type: "{{instance_type}}"
    count: "{{count}}"
    image: "{{image}}"
    region: "{{region}}"
    vpc_subnet_id: "{{vpc_subnet_id}}"
    keypair: "{{keypair}}"
    group: "{{group}}"
    assign_public_ip: "{{assign_public_ip}}"
    instance_tags: "{{instance_tags}}"
    source_dest_check: "{{source_dest_check}}"
    id: "{{id}}"
    wait: "{{wait}}"
  register: ec2_info

- debug: var=ec2_info

- debug: var=item
  with_items: ec2_info.instance_ids

- add_host: hostname={{item.public_ip}} groupname=tag_Name_{{group}}
  with_items: ec2_info.instances

- set_fact:
    bastion_id: "{{item.id}}"
  with_items: "{{ec2_info.instances}}"

- name: update bastion_id_{{region_name}} to "{{bastion_id}}"
  replace:
     dest: "/{{group_vars_path}}all/main.yml"
     regexp: "^bastion_id_{{region_name}}:.*$"
     replace: "bastion_id_{{region_name}}: {{bastion_id}}"

- name: wait for instances to listen on port:22
  wait_for:
    state: started
    host: "{{item.public_dns_name}}"
    port: 22
  with_items: ec2_info.instances
