---
- name: launch an ec2 instance
  ec2:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    instance_type: "{{instance_type}}"
    count: "{{count}}"
    image: "{{image}}"
    region: "{{region}}"
    vpc_subnet_id: "{{vpc_subnet_id}}"
    keypair: "{{keypair}}"
    group: "{{group}}"
    assign_public_ip: "{{assign_public_ip}}"
    instance_tags: "{{instance_tags}}"
    wait: "{{wait}}"
  register: ec2_info

- debug: var=ec2_info

- debug: var=item
  with_items: ec2_info.instance_ids

- add_host: hostname={{item.public_ip}} groupname=tag_Name_{{group}}
  with_items: ec2_info.instances

- set_fact:
    vpn_ip: "{{item.public_ip}}"
  with_items: "{{ec2_info.instances}}"

- name: remove old {{group_vars_path}}tag_Name_{{group}}"
  file:
    path: "/{{group_vars_path}}tag_Name_{{group}}"
    state: absent
    
- name: update vpn_ip var to {{vpn_ip}}
  lineinfile:
    dest: "/{{group_vars_path}}tag_Name_{{group}}"
    line: "vpn_ip: {{vpn_ip}}"
    state: present
    create: true

- name: wait for instances to listen on port:22
  wait_for:
    state: started
    host: "{{item.public_dns_name}}"
    port: 22
  with_items: ec2_info.instances
